import Component from '../../components/Component.js';
import SidebarLayout from '../../layouts/SidebarLayout.js';
import InstructorTheoryService from '../../services/instructorTheoryService.js';
import { escapeHtml, stateMessage } from './InstructorHelpers.js';

const dateLabel=value=>new Date(`${value}T12:00:00`).toLocaleDateString('es-EC',{weekday:'long',day:'numeric',month:'long'});
const modalityLabel=value=>value==='presencial_regular'?'Curso regular':'Curso intensivo';

export default class InstructorTheoryView extends Component {
  async render(){
    try{
      const params=new URLSearchParams(location.search),section=params.get('section')||'dashboard';
      const [groupsResponse,dashboardResponse]=await Promise.all([InstructorTheoryService.groups(),InstructorTheoryService.dashboard()]);
      const groups=groupsResponse.data||[],dashboard=dashboardResponse.data||{};
      let body='';
      if(section==='groups')body=this.groups(groups);
      else if(section==='history')body=this.history(dashboard.history||[]);
      else if(section==='attendance')body=await this.attendance(groups,params);
      else body=this.dashboard(dashboard,groups);
      const content=`<div class="instructor-page instructor-theory-page"><header class="agenda-hero theory-dashboard-hero"><div><span class="agenda-eyebrow">Formación teórica</span><h1>Mis clases de teoría</h1><p>Organiza tus grupos, registra asistencia y consulta el avance de cada jornada.</p></div></header>
        <nav class="theory-section-nav" aria-label="Funciones de clases teóricas">${this.navItem('dashboard','Resumen',section)}${this.navItem('attendance','Tomar asistencia',section)}${this.navItem('groups','Mis grupos',section)}${this.navItem('history','Historial',section)}</nav>${body}</div>`;
      const layout=await SidebarLayout.render(content);setTimeout(()=>SidebarLayout.attachEventListeners(),0);return layout;
    }catch(error){const layout=await SidebarLayout.render(`<div class="alert alert-error">${escapeHtml(stateMessage(error))}</div>`);setTimeout(()=>SidebarLayout.attachEventListeners(),0);return layout;}
  }
  navItem(section,label,current){return `<a href="/instructor/theory?section=${section}" class="theory-section-nav__item ${current===section?'active':''}" ${current===section?'aria-current="page"':''}>${label}</a>`;}
  dashboard(data,groups){const summary=data.summary||{},next=data.upcoming;return `<section class="theory-dashboard-summary">
    <article><span>Grupos activos</span><strong>${Number(summary.groups||0)}</strong><small>Cursos bajo tu responsabilidad</small></article>
    <article><span>Estudiantes</span><strong>${Number(summary.students||0)}</strong><small>Alumnos asignados</small></article>
    <article><span>Jornadas registradas</span><strong>${Number(summary.attendanceDays||0)}</strong><small>Días con asistencia guardada</small></article>
    <article><span>Presentes registrados</span><strong>${Number(summary.present||0)}</strong><small>Marcaciones acumuladas</small></article></section>
    ${next?`<section class="theory-next-class"><div><span class="agenda-eyebrow">Próxima clase</span><h2>${escapeHtml(modalityLabel(next.modality))}</h2><p>${escapeHtml(dateLabel(next.date))} · ${escapeHtml(next.startTime)}–${escapeHtml(next.endTime)} · ${next.students}/30 estudiantes</p></div><a class="btn btn-primary" href="/instructor/theory?section=attendance&group=${encodeURIComponent(next.groupId)}&date=${next.date}">Tomar asistencia</a></section>`:'<div class="instructor-empty"><strong>No existen próximas jornadas programadas.</strong></div>'}
    <section class="theory-dashboard-actions"><a href="/instructor/theory?section=groups"><span>Mis grupos</span><strong>Consultar estudiantes y fechas del curso</strong><small>${groups.length} grupos registrados →</small></a><a href="/instructor/theory?section=history"><span>Historial de asistencia</span><strong>Revisar jornadas ya registradas</strong><small>${Number(summary.attendanceDays||0)} jornadas guardadas →</small></a></section>`;}
  groups(groups){return `<section class="agenda-list-card"><div class="agenda-list-card__header"><div><span class="agenda-eyebrow">Organización</span><h2>Mis grupos teóricos</h2></div><span class="agenda-result-count">${groups.length} grupos</span></div><div class="theory-group-grid">${groups.map(group=>`<article><div><span class="theory-group-status">${escapeHtml(group.status)}</span><h3>${escapeHtml(modalityLabel(group.modality))}</h3><p>${escapeHtml(group.start_date)} al ${escapeHtml(group.end_date)}</p></div><strong>${escapeHtml(String(group.start_time).slice(0,5))}–${escapeHtml(String(group.end_time).slice(0,5))}</strong><span>${Number(group.students||0)}/30 estudiantes</span><div class="theory-group-dates">${group.classDates.map(date=>`<small>${escapeHtml(dateLabel(date))}</small>`).join('')}</div><a class="btn btn-secondary" href="/instructor/theory?section=attendance&group=${encodeURIComponent(group.id)}">Abrir asistencia</a></article>`).join('')||'<div class="instructor-empty"><strong>No tienes grupos asignados.</strong></div>'}</div></section>`;}
  history(rows){return `<section class="agenda-list-card"><div class="agenda-list-card__header"><div><span class="agenda-eyebrow">Seguimiento</span><h2>Historial de asistencia</h2></div><span class="agenda-result-count">${rows.length} jornadas</span></div><div class="theory-history-list">${rows.map(row=>`<article><div><strong>${escapeHtml(dateLabel(row.class_date))}</strong><small>${escapeHtml(modalityLabel(row.modality))} · ${escapeHtml(row.start_time)}–${escapeHtml(row.end_time)}</small></div><div><span class="present">${Number(row.present||0)} presentes</span><span class="absent">${Number(row.absent||0)} ausentes</span>${Number(row.justified||0)?`<span>${Number(row.justified)} justificados</span>`:''}</div><a class="btn btn-secondary btn-small" href="/instructor/theory?section=attendance&group=${encodeURIComponent(row.group_id)}&date=${row.class_date}">Ver clase</a></article>`).join('')||'<div class="instructor-empty"><strong>Todavía no has registrado asistencias.</strong></div>'}</div></section>`;}
  async attendance(groups,params){const groupId=params.get('group')||groups.find(item=>item.status!=='finalizado')?.id||groups[0]?.id;const roster=groupId?(await InstructorTheoryService.roster(groupId)).data:null;const selectedDate=params.get('date')||roster?.group?.classDates?.[0]||'';return `<section class="agenda-filter-card"><div class="form-row"><div class="form-group"><label class="form-label">Grupo</label><select class="form-select" id="theory-group-select">${groups.map(group=>`<option value="${group.id}" ${group.id===groupId?'selected':''}>${modalityLabel(group.modality)} · ${String(group.start_time).slice(0,5)} · ${group.start_date} · ${group.students}/30</option>`).join('')}</select></div>${roster?`<div class="form-group"><label class="form-label">Fecha de clase</label><select class="form-select" id="theory-date-select">${roster.group.classDates.map(date=>`<option value="${date}" ${date===selectedDate?'selected':''}>${dateLabel(date)}</option>`).join('')}</select></div>`:''}</div></section>${roster?this.table(roster,selectedDate):'<div class="instructor-empty"><strong>No tienes grupos teóricos asignados.</strong></div>'}`;}
  table(roster,date){return `<section class="agenda-list-card theory-attendance-card"><div class="agenda-list-card__header"><div><span class="agenda-eyebrow">${escapeHtml(dateLabel(date))}</span><h2>${modalityLabel(roster.group.modality)} · ${String(roster.group.start_time).slice(0,5)}–${String(roster.group.end_time).slice(0,5)}</h2></div><span class="agenda-result-count">${roster.students.length}/30 estudiantes</span></div><form id="theory-attendance-form"><input type="hidden" name="classDate" value="${date}"><div class="table-responsive theory-attendance-list"><table class="data-table"><thead><tr><th>Estudiante</th><th>Cédula</th><th>Asistencia</th><th>Observación</th></tr></thead><tbody>${roster.students.map(student=>{const present=student.attendance?.[date]==='presente';return `<tr data-student="${student.student_id}"><td data-label="Estudiante"><strong>${escapeHtml(student.student)}</strong></td><td data-label="Cédula">${escapeHtml(student.identification)}</td><td data-label="Asistencia"><label class="theory-attendance-check"><input type="checkbox" name="present" ${present?'checked':''}><span class="theory-attendance-check__box">✓</span><strong class="theory-attendance-check__label">${present?'Presente':'Ausente'}</strong></label></td><td data-label="Observación"><input class="form-input" name="observation" placeholder="Opcional"></td></tr>`}).join('')}</tbody></table></div><div class="modal-footer theory-attendance-actions"><span id="theory-save-status"></span><button class="btn btn-primary" type="submit" ${roster.students.length?'':'disabled'}>Guardar asistencia</button></div></form></section>`;}
  async mount(){const navigate=()=>{const group=document.getElementById('theory-group-select')?.value||'',date=document.getElementById('theory-date-select')?.value||'';history.pushState(null,null,`/instructor/theory?section=attendance&group=${encodeURIComponent(group)}${date?`&date=${date}`:''}`);window.dispatchEvent(new PopStateEvent('popstate'));};document.getElementById('theory-group-select')?.addEventListener('change',navigate);document.getElementById('theory-date-select')?.addEventListener('change',navigate);document.querySelectorAll('.theory-attendance-check input').forEach(input=>input.addEventListener('change',()=>{input.closest('.theory-attendance-check').querySelector('.theory-attendance-check__label').textContent=input.checked?'Presente':'Ausente';}));document.getElementById('theory-attendance-form')?.addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter,status=document.getElementById('theory-save-status');try{button.disabled=true;status.textContent='Guardando...';const records=[...event.currentTarget.querySelectorAll('tbody tr')].map(row=>({studentId:row.dataset.student,status:row.querySelector('[name=present]').checked?'presente':'ausente',observation:row.querySelector('[name=observation]').value}));await InstructorTheoryService.save(new URLSearchParams(location.search).get('group')||document.getElementById('theory-group-select').value,{classDate:event.currentTarget.elements.classDate.value,records});status.textContent='Asistencia guardada correctamente.';}catch(error){status.textContent=stateMessage(error);button.disabled=false;}});}
}
