import Component from '../../components/Component.js';
import SidebarLayout from '../../layouts/SidebarLayout.js';
import InstructorReferralService from '../../services/instructorReferralService.js';
import { escapeHtml, stateMessage } from './InstructorHelpers.js';

const formatDate=value=>value?new Date(`${String(value).slice(0,10)}T12:00:00`).toLocaleDateString('es-EC',{day:'numeric',month:'long',year:'numeric'}):'—';
const formatTime=value=>String(value||'').slice(0,5);

class InstructorReferralsView extends Component {
  async render() {
    try {
      const result=await InstructorReferralService.getAll(); this.students=result.data||[]; this.cycles=result.cycles||[];
      const active=this.students.filter(item=>item.reservation_id).length;
      const content=`<div class="instructor-page referral-page"><header class="referral-hero"><div><span class="agenda-eyebrow">Próximos cursos</span><h1>Cupos para mis referidos</h1><p>Separa un lugar para que tu estudiante pueda ingresar en una fecha de inicio futura.</p></div><button class="btn btn-primary" id="new-referral-seat">Reservar cupo</button></header>
      <section class="referral-summary"><article><small>Referidos activos</small><strong>${this.students.length}</strong></article><article><small>Con cupo reservado</small><strong>${active}</strong></article><article><small>Pendientes de reservar</small><strong>${Math.max(this.students.length-active,0)}</strong></article></section>
      <section class="referral-card"><div class="referral-card__head"><div><h2>Reservas de próximo inicio</h2><p>La reserva protege un cupo general del curso; el horario práctico se elegirá después durante la inscripción.</p></div></div><div class="referral-list">${this.students.length?this.students.map(item=>this.renderStudent(item)).join(''):'<div class="instructor-empty"><strong>Todavía no tienes estudiantes referidos.</strong><span>Cuando Secretaría registre un estudiante con tu nombre como referido, aparecerá aquí.</span></div>'}</div></section></div>`;
      const layout=await SidebarLayout.render(content);setTimeout(()=>SidebarLayout.attachEventListeners(),0);return layout;
    }catch(error){const layout=await SidebarLayout.render(`<div class="alert alert-error">${stateMessage(error)}</div>`);setTimeout(()=>SidebarLayout.attachEventListeners(),0);return layout;}
  }

  renderStudent(item){const reservedTime=item.reserved_start_time&&item.reserved_end_time?` · ${formatTime(item.reserved_start_time)} – ${formatTime(item.reserved_end_time)}`:'';return `<article class="referral-row"><div class="referral-avatar">${escapeHtml(item.student_name.split(' ').map(part=>part[0]).slice(0,2).join(''))}</div><div class="referral-person"><strong>${escapeHtml(item.student_name)}</strong><span>${escapeHtml(item.identification)} · ${escapeHtml(item.course_name)}</span><small>${escapeHtml(item.branch_name)}${item.phone?` · ${escapeHtml(item.phone)}`:''}</small></div>${item.reservation_id?`<div class="referral-seat is-reserved"><small>Cupo y horario reservados</small><strong>${escapeHtml(item.reserved_cycle_code)}</strong><span>Inicia ${formatDate(item.reserved_start_date)}${reservedTime}</span></div><button class="btn btn-secondary btn-small js-cancel-seat" data-id="${item.reservation_id}">Cancelar</button>`:`<div class="referral-seat"><small>Estado</small><strong>Sin reserva</strong><span>Puede seleccionar un próximo inicio</span></div><button class="btn btn-primary btn-small js-reserve-seat" data-enrollment="${item.enrollment_id}">Reservar</button>`}</article>`;}

  async mount(){document.getElementById('new-referral-seat')?.addEventListener('click',()=>this.openModal());document.querySelectorAll('.js-reserve-seat').forEach(button=>button.addEventListener('click',()=>this.openModal(button.dataset.enrollment)));document.querySelectorAll('.js-cancel-seat').forEach(button=>button.addEventListener('click',async()=>{if(!confirm('¿Cancelar esta reserva de cupo?'))return;try{button.disabled=true;await InstructorReferralService.cancel(button.dataset.id);window.dispatchEvent(new PopStateEvent('popstate'));}catch(error){alert(stateMessage(error));button.disabled=false;}}));}

  openModal(selectedEnrollment='') {
    const overlay=document.createElement('div');overlay.className='modal-overlay active referral-seat-overlay';
    const courseOptions=[...new Map(this.cycles.map(item=>[item.course_id,{id:item.course_id,name:item.course_name}])).values()];
    const branchOptions=[...new Map(this.cycles.map(item=>[item.branch_id,{id:item.branch_id,name:item.branch_name}])).values()];
    overlay.innerHTML=`<div class="modal referral-seat-modal"><div class="modal-header"><div><h3 class="modal-title">Reservar próximo inicio</h3><p>Protege un cupo y un horario práctico según la disponibilidad real del instructor.</p></div><button class="modal-close" type="button" data-close>&times;</button></div><form><div class="modal-body referral-seat-form"><label><span>Referido ya registrado (opcional)</span><select class="form-select" name="enrollmentId"><option value="">Es una persona nueva</option>${this.students.filter(item=>item.enrollment_id&&(!item.reservation_id||item.enrollment_id===selectedEnrollment)).map(item=>`<option value="${item.enrollment_id}" data-course="${item.course_id}" data-branch="${item.branch_id}" data-name="${escapeHtml(item.student_name)}" ${item.enrollment_id===selectedEnrollment?'selected':''}>${escapeHtml(item.student_name)} · ${escapeHtml(item.course_name)}</option>`).join('')}</select></label><div class="referral-new-person"><label><span>Nombre del referido</span><input class="form-input" name="referredName" placeholder="Nombres y apellidos"></label><label><span>Teléfono</span><input class="form-input" name="referredPhone" placeholder="09..."></label><label><span>Cédula (opcional)</span><input class="form-input" name="referredIdentification"></label><label><span>Curso</span><select class="form-select" name="courseId"><option value="">Selecciona</option>${courseOptions.map(item=>`<option value="${item.id}">${escapeHtml(item.name)}</option>`).join('')}</select></label><label><span>Sucursal</span><select class="form-select" name="branchId"><option value="">Selecciona</option>${branchOptions.map(item=>`<option value="${item.id}">${escapeHtml(item.name)}</option>`).join('')}</select></label></div><label><span>Próximo inicio de curso</span><select class="form-select" name="cycleId" required></select></label><label><span>Horario práctico disponible</span><select class="form-select" name="scheduleTime" required><option value="">Selecciona primero el próximo inicio</option></select><small class="referral-schedule-help">Solo aparecen horarios libres durante todas las fechas prácticas del curso.</small></label><label><span>Observación opcional</span><textarea class="form-input" name="notes" maxlength="240"></textarea></label><p class="alert alert-error" hidden></p></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-close>Cancelar</button><button type="submit" class="btn btn-primary">Confirmar reserva</button></div></form></div>`;
    document.body.appendChild(overlay);
    overlay.querySelector('[name="referredPhone"]')?.closest('label')?.remove();
    const close=()=>overlay.remove();overlay.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',close));
    const student=overlay.querySelector('[name="enrollmentId"]'),course=overlay.querySelector('[name="courseId"]'),branch=overlay.querySelector('[name="branchId"]'),cycle=overlay.querySelector('[name="cycleId"]'),schedule=overlay.querySelector('[name="scheduleTime"]'),newFields=overlay.querySelector('.referral-new-person');
    const updateSchedule=()=>{const selected=this.cycles.find(item=>String(item.id)===String(cycle.value));const slots=selected?.availableSlots||[];schedule.innerHTML=`<option value="">${selected?(slots.length?'Selecciona un horario':'No hay horarios disponibles'):'Selecciona primero el próximo inicio'}</option>${slots.map(slot=>`<option value="${slot.startTime}-${slot.endTime}">${slot.startTime} – ${slot.endTime}</option>`).join('')}`;schedule.disabled=!slots.length;};
    const update=()=>{const registered=student.selectedOptions[0]?.value;newFields.hidden=Boolean(registered);const courseId=registered?student.selectedOptions[0].dataset.course:course.value;const branchId=registered?student.selectedOptions[0].dataset.branch:branch.value;const available=this.cycles.filter(item=>String(item.course_id)===String(courseId)&&String(item.branch_id)===String(branchId));cycle.innerHTML=`<option value="">Selecciona una fecha</option>${available.map(item=>`<option value="${item.id}" ${item.available<1||!(item.availableSlots||[]).length?'disabled':''}>${formatDate(item.start_date)} · ${escapeHtml(item.code)} · ${item.available} cupos disponibles</option>`).join('')}`;updateSchedule();};[student,course,branch].forEach(field=>field.addEventListener('change',update));cycle.addEventListener('change',updateSchedule);update();
    overlay.querySelector('form').addEventListener('submit',async event=>{event.preventDefault();const submit=event.submitter,error=overlay.querySelector('.alert-error');try{submit.disabled=true;error.hidden=true;await InstructorReferralService.reserve(Object.fromEntries(new FormData(event.currentTarget)));close();window.dispatchEvent(new PopStateEvent('popstate'));}catch(requestError){error.textContent=stateMessage(requestError);error.hidden=false;submit.disabled=false;}});
  }
}

export default InstructorReferralsView;
