import Component from '../../components/Component.js';
import SidebarLayout from '../../layouts/SidebarLayout.js';
import ManagerService from '../../services/ManagerService.js';

const money = value => new Intl.NumberFormat('es-EC', { style: 'currency', currency: 'USD' }).format(Number(value) || 0);
const number = value => new Intl.NumberFormat('es-EC').format(Number(value) || 0);
const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' })[char]);

export default class ManagerFinanceView extends Component {
  constructor(props={}) { super(props); this.selectedMetric='total'; }
  async render() { return SidebarLayout.render(`<main class="admin-dashboard manager-finance"><header class="admin-dashboard__header"><div><h1>Financiero</h1><p>Análisis de ingresos, cobros y cartera pendiente</p></div><button class="btn btn-secondary" id="finance-refresh" type="button">↻ Actualizar</button></header>
    <section class="dashboard-filters manager-filter-bar"><label>Sucursal<select id="finance-branch"><option value="">Todas las sucursales</option></select></label><label>Provincia<select id="finance-province"><option value="">Todas</option></select></label><label>Cantón / ciudad<select id="finance-city"><option value="">Todos</option></select></label><label>Tipo de curso<select id="finance-course-type"><option value="">Todos</option><option value="moto">Moto</option><option value="carro">Automóvil</option></select></label><label>Desde<input id="finance-from" type="date"></label><label>Hasta<input id="finance-to" type="date"></label><button class="btn btn-secondary" id="finance-clear-filters" type="button">Limpiar filtros</button></section>
    <div id="finance-status" class="dashboard-status"></div><section id="finance-kpis" class="dashboard-kpis finance-kpis dashboard-skeleton"></section>
    <div class="dashboard-columns"><section class="dashboard-panel" id="finance-categories-panel"><div class="panel-title"><h2>Ingresos por concepto</h2></div><div id="finance-categories"></div></section><section class="dashboard-panel" id="finance-methods-panel"><div class="panel-title"><h2>Métodos de pago</h2></div><div id="finance-methods"></div></section></div>
    <section class="dashboard-panel" id="finance-daily-panel"><div class="panel-title"><div><h2 id="finance-daily-title">Evolución diaria de ingresos</h2><small class="finance-chart-hint">Selecciona una fecha para filtrar todo el tablero.</small></div><div class="finance-chart-actions"><button type="button" class="finance-clear-selection" id="finance-restore-range" hidden>Volver al rango</button><button type="button" class="finance-clear-selection" id="finance-clear-selection" hidden>Mostrar todo</button></div></div><div id="finance-daily" class="finance-daily"></div></section>
    <section class="dashboard-panel"><div class="panel-title"><h2 id="finance-branches-title">Resultados por sucursal</h2></div><div id="finance-branches" class="dashboard-table-wrap"></div></section>
    <section class="dashboard-panel" id="finance-receivables-panel"><div class="panel-title"><h2>Cartera pendiente por curso</h2></div><div id="finance-receivables" class="dashboard-table-wrap"></div></section></main>`); }

  async mount() {
    const today=new Date(), from=new Date(today); from.setDate(today.getDate()-14); const local=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
    document.getElementById('finance-from').value=local(from); document.getElementById('finance-to').value=local(today);
    this.defaultDates={from:local(from),to:local(today)};
    document.getElementById('finance-refresh')?.addEventListener('click',()=>this.load()); document.getElementById('finance-clear-selection')?.addEventListener('click',()=>this.clearInteractiveSelection());
    document.getElementById('finance-kpis')?.addEventListener('click',event=>{const card=event.target.closest('[data-finance-metric]');if(card){this.allowMetricSelection=true;this.selectMetric(card.dataset.financeMetric);}});
    document.getElementById('finance-categories')?.addEventListener('click',event=>{const row=event.target.closest('[data-finance-category]');if(row){this.allowMetricSelection=true;this.selectMetric(row.dataset.financeCategory);}});
    document.getElementById('finance-methods')?.addEventListener('click',event=>{const row=event.target.closest('[data-payment-method]');if(row){this.allowMetricSelection=true;this.selectMetric(`method:${row.dataset.paymentMethod}`);}});
    document.getElementById('finance-daily')?.addEventListener('click',event=>{const row=event.target.closest('[data-finance-day]');if(!row)return;if(this.previewedDay===row.dataset.financeDay)this.clearInteractiveSelection();else{this.previewDay(row.dataset.financeDay);document.getElementById('finance-clear-selection').hidden=false;}});
    document.getElementById('finance-province')?.addEventListener('change',()=>{document.getElementById('finance-city').value='';document.getElementById('finance-branch').value='';this.syncLocations();this.load();});
    document.getElementById('finance-city')?.addEventListener('change',()=>{document.getElementById('finance-branch').value='';this.syncLocations();this.load();}); document.getElementById('finance-branch')?.addEventListener('change',()=>this.load());
    document.getElementById('finance-course-type')?.addEventListener('change',()=>this.load());
    ['finance-from','finance-to'].forEach(id=>document.getElementById(id)?.addEventListener('change',()=>{if(document.getElementById('finance-from').value&&document.getElementById('finance-to').value)this.load();}));
    document.getElementById('finance-clear-filters')?.addEventListener('click',()=>{document.getElementById('finance-province').value='';document.getElementById('finance-city').value='';document.getElementById('finance-branch').value='';document.getElementById('finance-course-type').value='';document.getElementById('finance-from').value=this.defaultDates.from;document.getElementById('finance-to').value=this.defaultDates.to;this.syncLocations();this.load();}); await this.load();
  }
  filters(){return{period:'custom',branchId:document.getElementById('finance-branch')?.value,province:document.getElementById('finance-province')?.value,city:document.getElementById('finance-city')?.value,courseType:document.getElementById('finance-course-type')?.value,dateFrom:document.getElementById('finance-from')?.value,dateTo:document.getElementById('finance-to')?.value};}
  fillLocations(options=[]){this.options=options;const province=document.getElementById('finance-province'),selected=province.value,values=[...new Set(options.map(item=>item.province).filter(Boolean))].sort();province.innerHTML='<option value="">Todas</option>'+values.map(value=>`<option value="${esc(value)}">${esc(value)}</option>`).join('');province.value=values.includes(selected)?selected:'';this.syncLocations(true);}
  syncLocations(preserve=false){const province=document.getElementById('finance-province'),city=document.getElementById('finance-city'),branch=document.getElementById('finance-branch'),oldCity=city.value,oldBranch=branch.value;const cities=[...new Set((this.options||[]).filter(item=>!province.value||item.province===province.value).map(item=>item.city).filter(Boolean))].sort();city.innerHTML='<option value="">Todos</option>'+cities.map(value=>`<option value="${esc(value)}">${esc(value)}</option>`).join('');city.value=cities.includes(oldCity)?oldCity:'';const branches=(this.options||[]).filter(item=>(!province.value||item.province===province.value)&&(!city.value||item.city===city.value));branch.innerHTML='<option value="">Todas las sucursales</option>'+branches.map(item=>`<option value="${esc(item.id)}">${esc(item.name)}</option>`).join('');if(preserve&&branches.some(item=>String(item.id)===oldBranch))branch.value=oldBranch;}
  async load(){const status=document.getElementById('finance-status'),button=document.getElementById('finance-refresh');status.textContent='Actualizando información financiera…';button.disabled=true;try{const response=await ManagerService.financial(this.filters());this.paint(response.data||{});status.textContent=`Actualizado ${new Date().toLocaleTimeString('es-EC',{hour:'2-digit',minute:'2-digit'})}`;}catch(error){status.textContent=error.message||'No se pudo cargar Financiero';status.classList.add('dashboard-error');}finally{button.disabled=false;}}
  paint(data){this.financeData=data;this.selectedMetric='total';this.fillLocations(data.branchOptions||[]);const k=data.kpis||{},m=data.movements||{},serviceIncome=Number(k.evaluation_collected||0)+Number(k.recovery_collected||0);const cards=[['total','Ingresos cobrados',money(k.collected),'Total efectivo del periodo'],['courses','Cursos y matrículas',money(k.course_collected),'Ingresos por formación'],['services','Servicios',money(serviceIncome),'Psicosensométricos y recuperaciones'],['pending','Cartera pendiente',money(k.pending),'Valores todavía por cobrar'],['transactions','Transacciones',number(Number(m.course_transactions||0)+Number(m.service_transactions||0)),'Cobros confirmados'],['voided','Anulaciones',money(m.voided_amount),'Movimientos anulados']];document.getElementById('finance-kpis').innerHTML=cards.map(item=>`<article class="dashboard-kpi manager-kpi finance-kpi${this.selectedMetric===item[0]?' is-selected':''}" data-finance-metric="${item[0]}" tabindex="0"><strong>${item[2]}</strong><span>${item[1]}</span><small>${item[3]}</small><em>Pasa el cursor para resaltar</em></article>`).join('');document.querySelectorAll('[data-finance-metric]').forEach(card=>{const preview=()=>this.selectMetric(card.dataset.financeMetric);const clear=()=>this.selectMetric('total');card.addEventListener('mouseenter',preview);card.addEventListener('mouseleave',clear);card.addEventListener('focus',preview);card.addEventListener('blur',clear);});this.renderInteractiveVisuals();
    this.renderBranches();
    this.renderReceivables(data);
  }
  selectMetric(metric){if(!this.allowMetricSelection)return;this.allowMetricSelection=false;this.previewedDay=null;this.selectedMetric=this.selectedMetric===metric&&metric!=='total'?'total':metric;document.querySelectorAll('[data-finance-metric]').forEach(card=>card.classList.toggle('is-selected',card.dataset.financeMetric===this.selectedMetric));this.renderInteractiveVisuals();document.getElementById('finance-clear-selection').hidden=this.selectedMetric==='total';}
  renderInteractiveVisuals(){const data=this.financeData||{},metric=this.selectedMetric,labels={total:'todos los ingresos',courses:'cursos y matrículas',services:'servicios',pending:'cartera pendiente',transactions:'transacciones',voided:'anulaciones'},method=metric.startsWith('method:')?metric.split(':')[1]:null,category=metric.startsWith('category:')?metric.split(':')[1]:null,methodInfo=(data.paymentMethods||[]).find(item=>item.code===method),categoryInfo=(data.incomeDistribution||[]).find(item=>item.code===category),label=methodInfo?`pagos en ${String(methodInfo.name).toLowerCase()}`:categoryInfo?String(categoryInfo.name).toLowerCase():labels[metric];const clear=document.getElementById('finance-clear-selection');clear.hidden=true;document.getElementById('finance-daily-title').textContent=`Evolución diaria · ${label}`;this.updateMainCardsForMethod(methodInfo,categoryInfo);
    const distribution=data.incomeDistribution||[],maxCategory=Math.max(...distribution.map(item=>Number(item.amount)||0),1),categories=document.getElementById('finance-categories');categories.innerHTML=distribution.filter(item=>item.available!==false||Number(item.amount)>0).map(item=>{const linkedMetric=item.code==='courses'?'courses':`category:${item.code}`,selected=metric==='total'||metric===linkedMetric||(metric==='services'&&['evaluations','recoveries'].includes(item.code));return`<div class="manager-income-row finance-linked-row${(category||['courses','services'].includes(metric))&&!selected?' is-dimmed':''}" data-finance-category="${linkedMetric}" data-category-code="${esc(item.code)}" tabindex="0"><div><strong>${esc(item.name)}</strong><span>${money(item.amount)}</span></div><div class="manager-income-track"><i style="width:${(Number(item.amount||0)/maxCategory)*100}%"></i></div></div>`;}).join('');
    const methods=document.getElementById('finance-methods'),methodAmount=item=>metric==='courses'?item.course_amount:metric==='services'?item.service_amount:category==='evaluations'?item.evaluation_amount:category==='recoveries'?item.recovery_amount:item.amount;methods.innerHTML=(data.paymentMethods||[]).map(item=>`<div class="finance-method finance-linked-row${method===item.code?' is-selected':''}" data-payment-method="${esc(item.code)}" tabindex="0"><div><strong>${esc(item.name)}</strong><small>${number(item.transactions)} transacciones</small></div><strong>${money(methodAmount(item))}</strong></div>`).join('');
    const valueFor=item=>metric==='courses'?Number(item.course_amount):metric==='services'?Number(item.evaluation_amount)+Number(item.recovery_amount):category==='evaluations'?Number(item.evaluation_amount):category==='recoveries'?Number(item.recovery_amount):method?Number(item[`${method}_amount`]):Number(item.amount);const daily=data.daily||[],maxDay=Math.max(...daily.map(valueFor),1),dailyContainer=document.getElementById('finance-daily');dailyContainer.innerHTML=daily.length?daily.map(item=>{const value=valueFor(item),day=String(item.movement_date).slice(0,10);return`<div class="finance-day${value===0?' is-zero':''}" data-finance-day="${day}" tabindex="0"><span>${new Date(`${day}T00:00:00`).toLocaleDateString('es-EC',{day:'2-digit',month:'short'})}</span><div><i style="width:${(value/maxDay)*100}%"></i></div><strong>${money(value)}</strong></div>`;}).join(''):'<p class="dashboard-empty">No hay ingresos en este rango.</p>';document.getElementById('finance-restore-range').hidden=true;
    const incomeMode=['total','courses','services'].includes(metric)||Boolean(method)||Boolean(category);document.getElementById('finance-daily-panel').classList.toggle('is-dimmed',!incomeMode);document.getElementById('finance-categories-panel').classList.toggle('is-dimmed',!incomeMode);document.getElementById('finance-methods-panel').classList.toggle('is-highlighted',metric==='transactions'||Boolean(method)||Boolean(category));document.getElementById('finance-receivables-panel').classList.toggle('is-highlighted',metric==='pending');this.renderBranches();
  }
  renderBranches(source=this.financeData){const data=source||{},metric=this.selectedMetric||'total',method=metric.startsWith('method:')?metric.split(':')[1]:null,category=metric.startsWith('category:')?metric.split(':')[1]:null,labels={total:'Ingresos por sucursal',courses:'Cursos por sucursal',services:'Servicios por sucursal',pending:'Cartera pendiente por sucursal',transactions:'Ingresos por sucursal',voided:'Ingresos por sucursal'},label=method?`Pagos en ${method} por sucursal`:category==='evaluations'?'Evaluaciones por sucursal':category==='recoveries'?'Recuperaciones por sucursal':labels[metric];const value=item=>metric==='pending'?Number(item.pending):metric==='courses'?Number(item.course_collected):metric==='services'?Number(item.evaluation_collected)+Number(item.recovery_collected):category==='evaluations'?Number(item.evaluation_collected):category==='recoveries'?Number(item.recovery_collected):method?Number(item[`${method}_collected`]):Number(item.collected);const rows=data.branches||[],total=rows.reduce((sum,item)=>sum+value(item),0);document.getElementById('finance-branches-title').textContent=label;document.getElementById('finance-branches').innerHTML=rows.length?`<table><thead><tr><th>Sucursal</th><th>${metric==='pending'?'Pendiente':'Valor seleccionado'}</th><th>Participación</th></tr></thead><tbody>${rows.map(item=>{const amount=value(item);return`<tr><td><strong>${esc(item.name)}</strong><small>${esc(item.city||'')}</small></td><td>${money(amount)}</td><td>${total?((amount/total)*100).toFixed(1):'0.0'}%</td></tr>`;}).join('')}</tbody></table>`:'<p class="dashboard-empty">No hay sucursales para mostrar.</p>';}
  renderReceivables(data=this.financeData){document.getElementById('finance-receivables').innerHTML=data?.receivables?.length?`<table><thead><tr><th>Curso</th><th>Cuentas</th><th>Pendiente</th></tr></thead><tbody>${data.receivables.map(item=>`<tr><td>${esc(item.course_name)}</td><td>${number(item.accounts)}</td><td>${money(item.pending)}</td></tr>`).join('')}</tbody></table>`:'<p class="dashboard-empty">No existe cartera pendiente en la selección.</p>';}
  async loadDaySections(day){try{const response=await ManagerService.financial({...this.filters(),dateFrom:day,dateTo:day});if(this.previewedDay!==day)return;const data=response.data||{};this.renderBranches(data);this.renderReceivables(data);}catch(error){console.error('No se pudo cargar el detalle financiero del día',error);}}
  previewDay(day){if(this.previewedDay===day)return;this.previewedDay=day;const item=(this.financeData?.daily||[]).find(row=>String(row.movement_date).slice(0,10)===day);if(!item)return;const set=(metric,value)=>{const target=document.querySelector(`[data-finance-metric="${metric}"] strong`);if(target)target.textContent=value;};set('total',money(item.amount));set('courses',money(item.course_amount));set('services',money(Number(item.evaluation_amount)+Number(item.recovery_amount)));set('transactions',number(item.transactions));document.querySelectorAll('[data-finance-metric="pending"],[data-finance-metric="voided"]').forEach(card=>card.classList.add('is-dimmed'));(this.financeData.paymentMethods||[]).forEach(method=>{const target=document.querySelector(`[data-payment-method="${method.code}"]>strong`);if(target)target.textContent=money(item[`${method.code}_amount`]);});const categoryValues={courses:item.course_amount,evaluations:item.evaluation_amount,recoveries:item.recovery_amount};Object.entries(categoryValues).forEach(([code,value])=>{const target=document.querySelector(`[data-category-code="${code}"] span`);if(target)target.textContent=money(value);});document.getElementById('finance-daily-title').textContent=`Detalle financiero · ${new Date(`${day}T00:00:00`).toLocaleDateString('es-EC',{dateStyle:'long'})}`;document.querySelectorAll('[data-finance-day]').forEach(row=>row.classList.toggle('is-selected',row.dataset.financeDay===day));this.loadDaySections(day);}
  restoreDayPreview(){if(!this.previewedDay)return;this.previewedDay=null;this.paint(this.financeData);}
  clearInteractiveSelection(){this.previewedDay=null;this.selectedMetric='total';this.paint(this.financeData);}
  updateMainCardsForMethod(methodInfo,categoryInfo){const k=this.financeData?.kpis||{},m=this.financeData?.movements||{},set=(metric,value)=>{const target=document.querySelector(`[data-finance-metric="${metric}"] strong`);if(target)target.textContent=value;};set('total',money(k.collected));set('courses',money(k.course_collected));set('services',money(Number(k.evaluation_collected||0)+Number(k.recovery_collected||0)));set('transactions',number(Number(m.course_transactions||0)+Number(m.service_transactions||0)));if(methodInfo){set('total',money(methodInfo.amount));set('courses',money(methodInfo.course_amount));set('services',money(methodInfo.service_amount));set('transactions',number(methodInfo.transactions));}else if(categoryInfo){set('total',money(categoryInfo.amount));set('services',money(categoryInfo.amount));}}
}
