import Component from '../../components/Component.js';
import SidebarLayout from '../../layouts/SidebarLayout.js';
import { authService } from '../../core/auth/AuthService.js';
import ReferralCampaignService from '../../services/ReferralCampaignService.js';

const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' })[char]);
const statusName = value => ({ interesado:'Interesado',contactado:'Contactado',visita_programada:'Visita programada',matriculado:'Matriculado',no_concretado:'No concretado' })[value] || value;

export default class AdminReferralCampaignView extends Component {
  constructor(props = {}) { super(props); this.participantFilters = {}; this.leadFilters = {}; this.participants = []; this.leads = []; }
  canManage() { return authService.can('REFERRAL_CAMPAIGN_MANAGE'); }
  async load() {
    const [participants, leads] = await Promise.all([
      ReferralCampaignService.participants(this.participantFilters),
      ReferralCampaignService.leads(this.leadFilters),
    ]);
    if (!participants.success || !leads.success) throw new Error(participants.error || leads.error || 'No se pudo consultar la campaña');
    this.participants = participants.data || []; this.leads = leads.data || [];
  }
  async render() {
    try { await this.load(); } catch (error) { this.error = error.message; }
    return SidebarLayout.render(`<main class="referral-page"><style>
      .referral-page{padding:28px;max-width:1500px;margin:auto}.referral-head{display:flex;justify-content:space-between;gap:20px;align-items:center}.referral-tabs{display:flex;gap:8px;margin:20px 0}.referral-tab{border:1px solid #d0d5dd;background:#fff;border-radius:9px;padding:10px 16px;font-weight:700;cursor:pointer}.referral-tab.active{background:#5145e5;color:#fff}.referral-panel{background:#fff;border:1px solid #e4e7ec;border-radius:14px;overflow:hidden}.referral-filters{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:10px;padding:16px;background:#f8fafc}.referral-filters input,.referral-filters select{height:42px;border:1px solid #d0d5dd;border-radius:8px;padding:0 10px}.referral-table-wrap{overflow:auto}.referral-table{width:100%;border-collapse:collapse;min-width:900px}.referral-table th,.referral-table td{padding:12px;border-bottom:1px solid #eaecf0;text-align:left;font-size:13px}.referral-table th{background:#f9fafb}.referral-actions{display:flex;gap:6px;flex-wrap:wrap}.referral-actions button{border:1px solid #d0d5dd;background:#fff;border-radius:7px;padding:7px 9px;cursor:pointer}.referral-code{font-family:monospace;font-weight:700}.referral-badge{display:inline-block;padding:5px 9px;border-radius:99px;background:#eef2ff;color:#4338ca}.referral-badge.off{background:#fee2e2;color:#b42318}.referral-modal{position:fixed;inset:0;background:#10182899;display:grid;place-items:center;z-index:1000;padding:20px}.referral-modal-card{background:#fff;padding:24px;border-radius:16px;text-align:center;max-width:420px;width:100%}.referral-modal-card img{width:260px;max-width:100%}@media(max-width:800px){.referral-page{padding:14px}.referral-head{align-items:flex-start;flex-direction:column}.referral-filters{grid-template-columns:1fr}.referral-tabs{overflow:auto}}
    </style><header class="referral-head"><div><h1>Campaña de referidos</h1><p>Personal autorizado de Flavio Reyes, enlaces, interesados y conversiones.</p></div><div><strong>${this.participants.reduce((sum,row)=>sum+Number(row.interested||0),0)}</strong> interesados · <strong>${this.participants.reduce((sum,row)=>sum+Number(row.enrolled||0),0)}</strong> matriculados</div></header>${this.error?`<div class="alert alert-error">${esc(this.error)}</div>`:''}<nav class="referral-tabs"><button class="referral-tab active" data-panel="participants">Participantes</button><button class="referral-tab" data-panel="leads">Interesados</button></nav><section id="referral-participants" class="referral-panel">${this.participantPanel()}</section><section id="referral-leads" class="referral-panel" hidden>${this.leadPanel()}</section><div id="referral-modal"></div></main>`);
  }
  participantPanel() { return `<form class="referral-filters" id="participant-filters"><input name="search" placeholder="Buscar colaborador"><input name="role" placeholder="Rol"><select name="active"><option value="">Todos</option><option value="true">Activos</option><option value="false">Sin código activo</option></select><button class="btn btn-primary">Filtrar</button></form><div class="referral-table-wrap"><table class="referral-table"><thead><tr><th>Colaborador</th><th>Rol</th><th>Código</th><th>Visitas</th><th>Interesados</th><th>Matriculados</th><th>Conversión</th><th>Acciones</th></tr></thead><tbody>${this.participants.map(row=>`<tr><td><strong>${esc(row.name)}</strong><br><small>${esc(row.branch_name)}</small></td><td>${esc(row.role)}</td><td>${row.active?`<span class="referral-code">${esc(row.public_code)}</span>`:'<span class="referral-badge off">Inactivo</span>'}</td><td>${row.visits}</td><td>${row.interested}</td><td>${row.enrolled}</td><td>${row.conversionRate}%</td><td><div class="referral-actions">${row.active?`<button data-copy="${esc(row.referral_url)}">Copiar enlace</button><button data-qr="${esc(row.referral_url)}" data-name="${esc(row.name)}">QR</button>${this.canManage()?`<button data-action="disable" data-user="${row.id}">Desactivar</button><button data-action="regenerate" data-user="${row.id}">Regenerar</button>`:''}`:this.canManage()?`<button data-action="enable" data-user="${row.id}">Activar</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="8">No hay participantes para estos filtros.</td></tr>'}</tbody></table></div>`; }
  leadPanel() { const statuses=['interesado','contactado','visita_programada','matriculado','no_concretado']; return `<form class="referral-filters" id="lead-filters"><select name="status"><option value="">Todos los estados</option>${statuses.map(s=>`<option value="${s}">${statusName(s)}</option>`).join('')}</select><input type="date" name="date_from"><input type="date" name="date_to"><button class="btn btn-primary">Filtrar</button></form><div class="referral-table-wrap"><table class="referral-table"><thead><tr><th>Registro</th><th>Interesado</th><th>Curso / sede</th><th>Referido por</th><th>Estado</th></tr></thead><tbody>${this.leads.map(row=>`<tr><td><strong>${esc(row.tracking_code)}</strong><br><small>${new Date(row.created_at).toLocaleString('es-EC')}</small></td><td>${esc(row.full_name)}<br><small>${esc(row.identification)} · ${esc(row.whatsapp)}</small></td><td>${esc(row.course_interest)}<br><small>${esc(row.preferred_branch)} · ${esc(row.preferred_canton)}</small></td><td>${esc(row.worker||'Campaña general')}<br><small>${esc(row.referral_branch||'')}</small></td><td>${this.canManage()&&row.status!=='matriculado'?`<select data-lead-status="${row.id}">${statuses.filter(s=>s!=='matriculado').map(s=>`<option value="${s}" ${s===row.status?'selected':''}>${statusName(s)}</option>`).join('')}</select>`:`<span class="referral-badge">${statusName(row.status)}</span>`}</td></tr>`).join('')||'<tr><td colspan="5">No hay interesados para estos filtros.</td></tr>'}</tbody></table></div>`; }
  async refresh(panel) { await this.load(); document.getElementById('referral-participants').innerHTML=this.participantPanel(); document.getElementById('referral-leads').innerHTML=this.leadPanel(); this.bindPanels(); if(panel) document.querySelector(`[data-panel="${panel}"]`)?.click(); }
  bindPanels() {
    document.getElementById('participant-filters')?.addEventListener('submit',async event=>{event.preventDefault();this.participantFilters=Object.fromEntries(new FormData(event.currentTarget));await this.refresh('participants');});
    document.getElementById('lead-filters')?.addEventListener('submit',async event=>{event.preventDefault();this.leadFilters=Object.fromEntries(new FormData(event.currentTarget));await this.refresh('leads');});
    document.querySelectorAll('[data-copy]').forEach(button=>button.onclick=async()=>{await navigator.clipboard.writeText(button.dataset.copy);button.textContent='Copiado';});
    document.querySelectorAll('[data-qr]').forEach(button=>button.onclick=()=>{const url=`https://api.qrserver.com/v1/create-qr-code/?size=320x320&data=${encodeURIComponent(button.dataset.qr)}`;document.getElementById('referral-modal').innerHTML=`<div class="referral-modal"><div class="referral-modal-card"><h2>${esc(button.dataset.name)}</h2><img src="${url}" alt="Código QR del enlace de referido"><p class="referral-code">${esc(button.dataset.qr)}</p><a class="btn btn-primary" href="${url}" download="referido-qr.png">Descargar QR</a> <button class="btn" id="close-referral-modal">Cerrar</button></div></div>`;document.getElementById('close-referral-modal').onclick=()=>document.getElementById('referral-modal').innerHTML='';});
    document.querySelectorAll('[data-action]').forEach(button=>button.onclick=async()=>{const action=button.dataset.action;if((action==='disable'||action==='regenerate')&&!confirm(action==='disable'?'¿Desactivar este enlace?':'¿Regenerar el código? El enlace anterior dejará de funcionar.'))return;button.disabled=true;await ReferralCampaignService[action](button.dataset.user);await this.refresh('participants');});
    document.querySelectorAll('[data-lead-status]').forEach(select=>select.onchange=async()=>{await ReferralCampaignService.updateStatus(select.dataset.leadStatus,select.value);await this.refresh('leads');});
  }
  async mount() { document.querySelectorAll('[data-panel]').forEach(button=>button.onclick=()=>{document.querySelectorAll('.referral-tab').forEach(item=>item.classList.toggle('active',item===button));document.getElementById('referral-participants').hidden=button.dataset.panel!=='participants';document.getElementById('referral-leads').hidden=button.dataset.panel!=='leads';});this.bindPanels(); }
}
