import Component from '../../components/Component.js';
import SidebarLayout from '../../layouts/SidebarLayout.js';
import AdminService from '../../services/AdminService.js';

const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const num=(v,d=0)=>new Intl.NumberFormat('es-EC',{maximumFractionDigits:d}).format(Number(v)||0);
const bytes=v=>{const n=Number(v)||0,a=Math.abs(n);return a<1024?`${num(n)} B`:a<1048576?`${num(n/1024,1)} KB`:`${num(n/1048576,1)} MB`;};
const when=v=>v?new Date(v).toLocaleString('es-EC',{dateStyle:'short',timeStyle:'medium'}):'';
const labels={SESSION_START:'Inicio de sesión',SESSION_END:'Cierre de sesión',STUDENT_ENROLLMENT:'Inscripción',STUDENT_QUERY:'Consulta de estudiantes',STUDENT_OPERATION:'Gestión de estudiante',PAYMENT:'Pago',FINANCIAL_QUERY:'Consulta financiera',DOCUMENT_QUERY:'Consulta de documentos',DOCUMENT_OPERATION:'Gestión documental',ACADEMIC_QUERY:'Consulta académica',SCHEDULE_OPERATION:'Gestión de horario',INSTRUCTOR_QUERY:'Consulta de instructor',INSTRUCTOR_OPERATION:'Operación de instructor',INSTRUCTOR_ATTENDANCE:'Asistencia',ADDITIONAL_PRACTICE:'Práctica adicional',REPORT_QUERY:'Reporte',ADMIN_QUERY:'Consulta administrativa',ADMIN_OPERATION:'Configuración administrativa',NOTIFICATION_QUERY:'Notificaciones',SYSTEM_REQUEST:'Operación del sistema'};

export default class AdminResourceMonitorView extends Component {
  constructor(p={}){super(p);this.loading=false;this.paused=false;}
  async render(){return SidebarLayout.render(`<main class="resource-monitor">
    <header class="resource-monitor__header"><div><span>CAPACIDAD Y OPERACIÓN</span><h1>Recursos de todo el sistema</h1><p>Mide la sesión completa: accesos, consultas y operaciones de todos los módulos.</p></div><div class="enrollment-monitor__live"><i></i><strong>En vivo</strong><small id="resource-updated">Conectando…</small></div></header>
    <section class="enrollment-monitor__toolbar resource-monitor__toolbar"><label>Sucursal<select id="resource-branch"><option value="">Todas las sucursales</option></select></label><label>Periodo<select id="resource-hours"><option value="1">Última hora</option><option value="24" selected>Últimas 24 horas</option><option value="168">Últimos 7 días</option><option value="720">Últimos 30 días</option></select></label><button class="btn btn-secondary" id="resource-toggle">Pausar monitor</button><button class="btn btn-secondary" id="resource-export">Exportar Excel</button><button class="btn btn-primary" id="resource-refresh">Actualizar ahora</button></section>
    <div id="resource-error" class="dashboard-status" aria-live="polite"></div><section class="resource-monitor__cards" id="resource-cards"></section><section class="resource-monitor__recommendation" id="resource-sizing"></section>
    <div class="resource-monitor__columns"><section class="enrollment-monitor__panel"><div class="enrollment-monitor__panel-head"><div><h2>Estado del servidor</h2><p>Proceso Node.js y conexiones PostgreSQL.</p></div></div><div id="resource-server" class="resource-monitor__server"></div></section><section class="enrollment-monitor__panel"><div class="enrollment-monitor__panel-head"><div><h2>Cómo interpretar la medición</h2></div></div><div class="resource-monitor__explanation"><p><strong>CPU y consultas</strong> se atribuyen a cada petición.</p><p><strong>Memoria observada</strong> es la variación del proceso compartido y puede ser negativa.</p><p><strong>Privacidad:</strong> no se guardan contraseñas ni contenido de formularios.</p></div></section></div>
    <section class="enrollment-monitor__panel"><div class="enrollment-monitor__panel-head"><div><h2>Actividad técnica reciente</h2><p>Qué hizo cada persona y cuántos recursos utilizó.</p></div><span id="resource-count">0 operaciones</span></div><div class="dashboard-table-wrap" id="resource-table"></div></section></main>`);}
  async mount(){this.branch=document.getElementById('resource-branch');this.hours=document.getElementById('resource-hours');this.branch?.addEventListener('change',()=>this.load());this.hours?.addEventListener('change',()=>this.load());document.getElementById('resource-refresh')?.addEventListener('click',()=>this.load());document.getElementById('resource-export')?.addEventListener('click',()=>this.exportExcel());document.getElementById('resource-toggle')?.addEventListener('click',e=>{this.paused=!this.paused;e.currentTarget.textContent=this.paused?'Reanudar monitor':'Pausar monitor';document.querySelector('.enrollment-monitor__live')?.classList.toggle('paused',this.paused);if(!this.paused)this.load();});await this.load();this.timer=setInterval(()=>{if(!this.paused)this.load();},5000);}
  async exportExcel(){const button=document.getElementById('resource-export'),status=document.getElementById('resource-error');button.disabled=true;button.textContent='Generando Excel…';status.textContent='Preparando el archivo completo…';try{const file=await AdminService.exportResourceMonitor({branchId:this.branch?.value,hours:this.hours?.value});if(!file?.blob)throw new Error(file?.error||'No se recibió el archivo');const url=URL.createObjectURL(file.blob),link=document.createElement('a');link.href=url;link.download=file.filename;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);status.textContent='Excel descargado correctamente.';}catch(error){status.textContent=error.message||'No se pudo exportar el Excel.';}finally{button.disabled=false;button.textContent='Exportar Excel';}}
  async load(){if(this.loading)return;this.loading=true;try{const r=await AdminService.resourceMonitor({branchId:this.branch?.value,hours:this.hours?.value}),d=r.data||{};if(d.branches?.length&&this.branch?.options.length===1)this.branch.insertAdjacentHTML('beforeend',d.branches.map(x=>`<option value="${esc(x.id)}">${esc(x.name.trim())}</option>`).join(''));this.paint(d);document.getElementById('resource-error').textContent='';document.getElementById('resource-updated').textContent=`Actualizado ${new Date(d.serverTime).toLocaleTimeString('es-EC')}`;}catch(e){document.getElementById('resource-error').textContent=e.message||'No se pudo cargar la telemetría.';}finally{this.loading=false;}}
  paint(d){const s=d.summary||{},cards=[[s.sampleCount,'Operaciones medidas',`${num(s.enrollmentCount)} inscripciones`],[`${num(s.avgDurationMs,1)} ms`,'Tiempo promedio',`P95 ${num(s.p95DurationMs,1)} ms`],[`${num(s.avgCpuMs,1)} ms`,'CPU promedio',`P95 ${num(s.p95CpuMs,1)} ms`],[num(s.avgQueries,1),'Consultas promedio',`${num(s.avgDbMs,1)} ms en base`],[bytes(s.avgRequestBytes),'Entrada promedio','Datos recibidos'],[bytes(s.avgResponseBytes),'Salida promedio','Datos respondidos']];document.getElementById('resource-cards').innerHTML=cards.map(x=>`<article><strong>${esc(x[0])}</strong><span>${x[1]}</span><small>${x[2]}</small></article>`).join('');const z=d.sizing||{},box=document.getElementById('resource-sizing');box.className=`resource-monitor__recommendation ${esc(z.level)}`;box.innerHTML=`<div><strong>Lectura para dimensionar el servidor</strong><p>${esc(z.message)}</p></div><p>${esc(z.recommendation)}</p>`;const p=d.process||{},q=p.pool||{};document.getElementById('resource-server').innerHTML=`<dl><div><dt>Memoria del proceso</dt><dd>${bytes(p.rssBytes)}</dd></div><div><dt>Heap utilizado</dt><dd>${bytes(p.heapUsedBytes)}</dd></div><div><dt>Conexiones PostgreSQL</dt><dd>${num(q.total)} / ${num(q.max)}</dd></div><div><dt>Esperando conexión</dt><dd>${num(q.waiting)}</dd></div><div><dt>Tiempo activo</dt><dd>${num((p.uptimeSeconds||0)/3600,1)} h</dd></div><div><dt>Node.js</dt><dd>${esc(p.nodeVersion)}</dd></div></dl>`;this.paintRows(d.rows||[]);}
  paintRows(rows){const target=document.getElementById('resource-table');document.getElementById('resource-count').textContent=`${rows.length} operaciones recientes`;if(!rows.length){target.innerHTML='<p class="dashboard-empty">Las nuevas operaciones aparecerán automáticamente.</p>';return;}target.innerHTML=`<table><thead><tr><th>Hora</th><th>Qué hizo</th><th>Responsable</th><th>Contexto</th><th>Resultado</th><th>Duración</th><th>CPU</th><th>Base de datos</th><th>Memoria</th><th>Red</th></tr></thead><tbody>${rows.map(r=>{const old=r.historical;return `<tr><td>${when(r.created_at)}</td><td><strong>${esc(r.action_description||labels[r.operation]||labels.SYSTEM_REQUEST)}</strong><small>${esc(labels[r.operation]||labels.SYSTEM_REQUEST)}</small></td><td><strong>${esc(r.actor_name||'Sistema / sin autenticar')}</strong></td><td>${esc(r.student_name||r.route||'Sin detalle')}<small>${esc(r.branch_name||'')}</small></td><td><span class="status-pill ${r.success?'active':'inactive'}">${r.success?'Correcto':`Error ${r.status_code}`}</span></td><td>${old?'Sin medición':`${num(r.duration_ms,1)} ms`}</td><td>${old?'—':`${num(r.cpu_ms,1)} ms`}</td><td>${old?'—':`${num(r.db_query_count)} consultas<small>${num(r.db_duration_ms,1)} ms</small>`}</td><td>${old?'—':bytes(r.heap_delta_bytes)}</td><td>${old?'—':bytes(Number(r.request_bytes)+Number(r.response_bytes))}</td></tr>`;}).join('')}</tbody></table>`;}
  unmount(){clearInterval(this.timer);super.unmount();}
}
